### Login
POST http://localhost:5000/api/auth/login HTTP/1.1
content-type: application/json

{
 "identity" : "tanacom0249@hotmail.com",
 "password" : "Jammy@1223_3432"
}
###  Register
}
POST http://localhost:5000/api/auth/register HTTP/1.1
content-type: application/json

{
 "identity" : "andy@cc20.th",
 "firstName" : "Andy",
 "lastName" : "Smith",
 "email" : "andy@cc20.th",
 "password" : "a1234",
 "role" : "Seller",
 "street" : "123 Main St",
 "city" : "Anytown",
 "postalCode" : "52212"
}



### Send OTP for Forgot Password
POST http://localhost:5000/api/auth/request-otp HTTP/1.1
{
    "email" : "thanacom0249@gmail.com"
}

### Get OTP after requesting 
POST http://localhost:5000/api/auth/verify-otp HTTP/1.1
content-type: application/json

{
  "email": "thanacom0249@gmail.com",
  "otp": "378156"
}

### Reset Password 
POST http://localhost:5000/api/auth/reset-password HTTP/1.1
content-type: application/json

{
 "email": "thanacom0249@gmail.com",
  "otp": "378156",
  "newPassword": "thanacom@22333"
}