### Login
POST http://localhost:5000/api/auth/login HTTP/1.1
content-type: application/json

{
 "identity" : "tanacom0249@hotmail.com",
 "password" : "Jammy@1223_3432"
}
###  Register
}
POST http://localhost:5000/api/auth/register HTTP/1.1
content-type: application/json

{
 "identity"   : "anddy333@gmail.com",
 "firstName"  : "Andy33",
 "lastName"   : "Smith333",
 "email"      : "anddy333@gmail.com",
 "username"   : "anddy333",
 "password"   : "123345333",
 "phone"      : "123433330",
 "role"       : "Seller",
 "street"     : "333 Main St",
 "city"       : "town",
 "postalCode" : "33312",
 "label"      : "Home",
 "state"      : "town",
 "country"    : "USA"

}



### Send OTP for Forgot Password
POST http://localhost:5000/api/auth/request-otp HTTP/1.1
{
    "email" : "thanacom0249@gmail.com"
}

### Get OTP after requesting 
POST http://localhost:5000/api/auth/verify-otp HTTP/1.1
content-type: application/json

{
  "email": "thanacom0249@gmail.com",
  "otp": "378156"
}

### Reset Password 
POST http://localhost:5000/api/auth/reset-password HTTP/1.1
content-type: application/json

{
 "email": "thanacom0249@gmail.com",
  "otp": "378156",
  "newPassword": "thanacom@22333"
}